name: background_task_example
description: "Demonstrates how to use the background_task plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  background_task: ^0.1.1+1



  cupertino_icons: ^1.0.2

  dio: ^5.4.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl:

  path_provider: ^2.1.2

  permission_handler: ^11.1.0

  shared_preferences: ^2.2.2

  map_launcher: ^3.1.0

  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  geolocator: ^11.0.0
  get: ^4.6.6

dev_dependencies:
  build_runner:

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter



  pedantic_mono:



flutter:
  uses-material-design: true
